#! /bin/sh

picom -b

feh --bg-fill ~/.wallpapers/mountain-night.jpg

~/.local/share/xborder/xborders --border-width 2 --border-radius 5 &

eww open workspaces
eww open system

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          15

bspc config left_padding 	50

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
